#  This packages all combat helpers into a single module for easier imports
from game.helpers.combat_helpers.apply_creature_effects import apply_creature_effects
from game.helpers.combat_helpers.apply_poison import apply_poison
from game.helpers.combat_helpers.create_beam import create_beam
from game.helpers.combat_helpers.create_bullet import create_bullet
from game.helpers.combat_helpers.handle_creature_collision import handle_creature_collision
from game.helpers.combat_helpers.handle_firing import handle_firing
from game.helpers.combat_helpers.handle_piercing_collision import handle_piercing_collision
from game.helpers.combat_helpers.handle_splash_damage import handle_splash_damage
from game.helpers.combat_helpers.reset_warm_up import reset_warm_up
from game.helpers.combat_helpers.update_bullets import update_bullets
from game.helpers.combat_helpers.update_burning_creatures import update_burning_creatures
from game.helpers.combat_helpers.update_poison_effects import update_poison_effects
